### ISSUE TITLE
Engine Routes with dynamic segments cannot be linked from the consuming app.

### ISSUE THREAD

**Issue by runspired** [dgeb/ember-engines#104]
Example Setup

Engine **routes.js**
```
  this.route('foo', { path: '/:id'});
```

App **router.js**
```
this.mount('<some-engine>', { as: 'my-engine', path: 'baz'});
```

App **application.hbs**
```
{{#link-to 'my-engine.foo' 1}} Link to Foo (1) {{/link-to}}
```

Example Error
```
ember.debug.js:18694 Error: Assertion Failed: You used the dynamic segment id in your route foo, but <app-name>.Foo did not exist and you did not override your route's `model` hook.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:33145:21)
    at assert (http://localhost:4200/assets/vendor.js:21159:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:32957:34)
    at Object.find (http://localhost:4200/assets/vendor.js:43463:28)
    at model (http://localhost:4200/assets/vendor.js:152988:32)
    at _emberRuntimeSystemObject.default.extend.deserialize (http://localhost:4200/assets/vendor.js:43430:19)
    at Object.applyHook (http://localhost:4200/assets/vendor.js:79140:30)
    at Object.HandlerInfo.runSharedModelHook (http://localhost:4200/assets/vendor.js:77329:33)
    at Object._routerUtils.subclass.getModel (http://localhost:4200/assets/vendor.js:77245:19)
```

**Comment by runspired** [comment]
Leaving a note for those weary spelunkers that come after me, having ventured on a long journey attempting to discover why their routes fail.

The real issue here is that Ember has provided a `store` service basically since the beginning, with an API that is close to `ember-data`, and which attempts a global lookup for model for you.

In an engine, even if you've shared the `store` service from your app to the engine, it has not yet been injected onto Route's and Controllers.  So the `store` property on a route or controller will refer to this Ember API, and not the `store` you might expect.

You'll want to either inject the store on just those routes / controllers where you need it, or you'll need to setup an initializer that injects it onto all routes and controllers for you.

<3
