### ISSUE TITLE
this.mount breaks router unit tests

### ISSUE THREAD

**Issue by dfalling** [dgeb/ember-engines#216]
I use Mocha/Chai to unit test my application's router.  After adding in a `this.mount` for my engine, the router test fails on `this.router._initRouterJs();`
```
  beforeEach(function(){
    this.router = appRouter.create();
    this.router._initRouterJs();
    this.routeNames = Object.keys(this.router.router.recognizer.names);
  });
```
```
TypeError: Cannot read property '_lookupFactory' of undefined
    at Object.resolveRouteMap (assets/vendor.js:166023:23)
    at Object.EmberRouterDSL.mount (assets/vendor.js:165914:39)
    at Object.<anonymous> (assets/documoto.js:18043:10)
    at Object.<anonymous> (assets/vendor.js:48669:27)
    at Object.route (assets/vendor.js:46213:18)
    at Class._initRouterJs (assets/vendor.js:48667:11)
    at Context.<anonymous> (assets/tests.js:11635:19)
    at invoke (assets/test-support.js:29427:21)
    at Context.asyncFn (assets/test-support.js:29412:11)
    at callFnAsync (assets/test-support.js:12413:21)
```

Is there any way to fix this?

Thanks!

**Comment by trentmwillis** [comment]
You likely need to run the provided initializer before your test, since that is what adds the `mount` keyword to the Router's DSL.

**Comment by nathanhammond** [comment]
Confirm that is the issue. Closing. If you have additional questions we all hang out in [#-ember-engines](https://embercommunity.slack.com/messages/-ember-engines/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/).
